output_dir: "./models"
num_train_epochs: 3
learning_rate: 0.00002
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
weight_decay: 0.01
eval_strategy: "epoch"
save_total_limit: 2
logging_dir: "./logs"
logging_steps: 100
max_grad_norm: 1.0
report_to: "wandb"
